nfs-driver:
  privileged: true
  image: rancher/storage-nfs:v0.0.2
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
  environment:
    HOST: '${NFS_SERVER}'
    EXPORT: '${MOUNT_DIR}'
    MOUNT_OPTS: '${MOUNT_OPTS}'
  volumes:
  - /run:/run
  - /dev:/host/dev
  metadata:
    storage_driver:
      name: rancher-nfs
      scope: environment
      volumeAccessMode: multiHostRW
